//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.05 at 08:49:53 AM MSK 
//


package eu.nimble.service.model.ubl.commonaggregatecomponents;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.nimble.service.model.ubl.commonbasiccomponents.AmountType;
import eu.nimble.service.model.ubl.commonbasiccomponents.TextType;
import org.hibernate.annotations.Cascade;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for CompletedTaskType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompletedTaskType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}AssociatedProcessInstanceID"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}AnnualAverageAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TotalTaskAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PartyCapacityAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Description" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}EvidenceSupplied" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}Period" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}RecipientCustomerParty" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}Comment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompletedTaskType", propOrder = {
    "associatedProcessInstanceID",
    "annualAverageAmount",
    "totalTaskAmount",
    "partyCapacityAmount",
    "description",
    "evidenceSupplied",
    "period",
    "recipientCustomerParty",
    "comment"
})
@Entity(name = "CompletedTaskType")
@Table(name = "COMPLETED_TASK_TYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class CompletedTaskType
    implements Serializable, Equals
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "AssociatedProcessInstanceID", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected String associatedProcessInstanceID;
    @XmlElement(name = "AnnualAverageAmount", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType annualAverageAmount;
    @XmlElement(name = "TotalTaskAmount", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType totalTaskAmount;
    @XmlElement(name = "PartyCapacityAmount", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType partyCapacityAmount;
    @XmlElement(name = "Description", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected List<TextType> description;
    @XmlElement(name = "EvidenceSupplied")
    protected List<EvidenceSuppliedType> evidenceSupplied;
    @XmlElement(name = "Period")
    protected PeriodType period;
    @XmlElement(name = "RecipientCustomerParty")
    protected CustomerPartyType recipientCustomerParty;
    @XmlElement(name = "Comment")
    protected List<CommentType> comment;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the associatedProcessInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ASSOCIATED_PROCESS_INSTANCE__0", length = 255)
    public String getAssociatedProcessInstanceID() {
        return associatedProcessInstanceID;
    }

    /**
     * Sets the value of the associatedProcessInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedProcessInstanceID(String value) {
        this.associatedProcessInstanceID = value;
    }

    /**
     * Gets the value of the annualAverageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "ANNUAL_AVERAGE_AMOUNT_COMPLE_0")
    public AmountType getAnnualAverageAmount() {
        return annualAverageAmount;
    }

    /**
     * Sets the value of the annualAverageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAnnualAverageAmount(AmountType value) {
        this.annualAverageAmount = value;
    }

    /**
     * Gets the value of the totalTaskAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "TOTAL_TASK_AMOUNT_COMPLETED__0")
    public AmountType getTotalTaskAmount() {
        return totalTaskAmount;
    }

    /**
     * Sets the value of the totalTaskAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTotalTaskAmount(AmountType value) {
        this.totalTaskAmount = value;
    }

    /**
     * Gets the value of the partyCapacityAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "PARTY_CAPACITY_AMOUNT_COMPLE_0")
    public AmountType getPartyCapacityAmount() {
        return partyCapacityAmount;
    }

    /**
     * Sets the value of the partyCapacityAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPartyCapacityAmount(AmountType value) {
        this.partyCapacityAmount = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    @OneToMany(orphanRemoval = true,targetEntity = TextType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "DESCRIPTION_COMPLETED_TASK_T_0")
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * 
     * 
     */
    public void setDescription(List<TextType> description) {
        this.description = description;
    }

    /**
     * Gets the value of the evidenceSupplied property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidenceSupplied property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidenceSupplied().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidenceSuppliedType }
     * 
     * 
     */
    @OneToMany(orphanRemoval = true,targetEntity = EvidenceSuppliedType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "EVIDENCE_SUPPLIED_COMPLETED__0")
    public List<EvidenceSuppliedType> getEvidenceSupplied() {
        if (evidenceSupplied == null) {
            evidenceSupplied = new ArrayList<EvidenceSuppliedType>();
        }
        return this.evidenceSupplied;
    }

    /**
     * 
     * 
     */
    public void setEvidenceSupplied(List<EvidenceSuppliedType> evidenceSupplied) {
        this.evidenceSupplied = evidenceSupplied;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    @ManyToOne(targetEntity = PeriodType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "PERIOD_COMPLETED_TASK_TYPE_H_0")
    public PeriodType getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setPeriod(PeriodType value) {
        this.period = value;
    }

    /**
     * Gets the value of the recipientCustomerParty property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPartyType }
     *     
     */
    @ManyToOne(targetEntity = CustomerPartyType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "RECIPIENT_CUSTOMER_PARTY_COM_0")
    public CustomerPartyType getRecipientCustomerParty() {
        return recipientCustomerParty;
    }

    /**
     * Sets the value of the recipientCustomerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPartyType }
     *     
     */
    public void setRecipientCustomerParty(CustomerPartyType value) {
        this.recipientCustomerParty = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentType }
     * 
     * 
     */
    @OneToMany(orphanRemoval = true,targetEntity = CommentType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "COMMENT__COMPLETED_TASK_TYPE_0")
    public List<CommentType> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentType>();
        }
        return this.comment;
    }

    /**
     * 
     * 
     */
    public void setComment(List<CommentType> comment) {
        this.comment = comment;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CompletedTaskType that = ((CompletedTaskType) object);
        {
            String lhsAssociatedProcessInstanceID;
            lhsAssociatedProcessInstanceID = this.getAssociatedProcessInstanceID();
            String rhsAssociatedProcessInstanceID;
            rhsAssociatedProcessInstanceID = that.getAssociatedProcessInstanceID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "associatedProcessInstanceID", lhsAssociatedProcessInstanceID), LocatorUtils.property(thatLocator, "associatedProcessInstanceID", rhsAssociatedProcessInstanceID), lhsAssociatedProcessInstanceID, rhsAssociatedProcessInstanceID)) {
                return false;
            }
        }
        {
            AmountType lhsAnnualAverageAmount;
            lhsAnnualAverageAmount = this.getAnnualAverageAmount();
            AmountType rhsAnnualAverageAmount;
            rhsAnnualAverageAmount = that.getAnnualAverageAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "annualAverageAmount", lhsAnnualAverageAmount), LocatorUtils.property(thatLocator, "annualAverageAmount", rhsAnnualAverageAmount), lhsAnnualAverageAmount, rhsAnnualAverageAmount)) {
                return false;
            }
        }
        {
            AmountType lhsTotalTaskAmount;
            lhsTotalTaskAmount = this.getTotalTaskAmount();
            AmountType rhsTotalTaskAmount;
            rhsTotalTaskAmount = that.getTotalTaskAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalTaskAmount", lhsTotalTaskAmount), LocatorUtils.property(thatLocator, "totalTaskAmount", rhsTotalTaskAmount), lhsTotalTaskAmount, rhsTotalTaskAmount)) {
                return false;
            }
        }
        {
            AmountType lhsPartyCapacityAmount;
            lhsPartyCapacityAmount = this.getPartyCapacityAmount();
            AmountType rhsPartyCapacityAmount;
            rhsPartyCapacityAmount = that.getPartyCapacityAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "partyCapacityAmount", lhsPartyCapacityAmount), LocatorUtils.property(thatLocator, "partyCapacityAmount", rhsPartyCapacityAmount), lhsPartyCapacityAmount, rhsPartyCapacityAmount)) {
                return false;
            }
        }
        {
            List<TextType> lhsDescription;
            lhsDescription = (((this.description!= null)&&(!this.description.isEmpty()))?this.getDescription():null);
            List<TextType> rhsDescription;
            rhsDescription = (((that.description!= null)&&(!that.description.isEmpty()))?that.getDescription():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "description", lhsDescription), LocatorUtils.property(thatLocator, "description", rhsDescription), lhsDescription, rhsDescription)) {
                return false;
            }
        }
        {
            List<EvidenceSuppliedType> lhsEvidenceSupplied;
            lhsEvidenceSupplied = (((this.evidenceSupplied!= null)&&(!this.evidenceSupplied.isEmpty()))?this.getEvidenceSupplied():null);
            List<EvidenceSuppliedType> rhsEvidenceSupplied;
            rhsEvidenceSupplied = (((that.evidenceSupplied!= null)&&(!that.evidenceSupplied.isEmpty()))?that.getEvidenceSupplied():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "evidenceSupplied", lhsEvidenceSupplied), LocatorUtils.property(thatLocator, "evidenceSupplied", rhsEvidenceSupplied), lhsEvidenceSupplied, rhsEvidenceSupplied)) {
                return false;
            }
        }
        {
            PeriodType lhsPeriod;
            lhsPeriod = this.getPeriod();
            PeriodType rhsPeriod;
            rhsPeriod = that.getPeriod();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "period", lhsPeriod), LocatorUtils.property(thatLocator, "period", rhsPeriod), lhsPeriod, rhsPeriod)) {
                return false;
            }
        }
        {
            CustomerPartyType lhsRecipientCustomerParty;
            lhsRecipientCustomerParty = this.getRecipientCustomerParty();
            CustomerPartyType rhsRecipientCustomerParty;
            rhsRecipientCustomerParty = that.getRecipientCustomerParty();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "recipientCustomerParty", lhsRecipientCustomerParty), LocatorUtils.property(thatLocator, "recipientCustomerParty", rhsRecipientCustomerParty), lhsRecipientCustomerParty, rhsRecipientCustomerParty)) {
                return false;
            }
        }
        {
            List<CommentType> lhsComment;
            lhsComment = (((this.comment!= null)&&(!this.comment.isEmpty()))?this.getComment():null);
            List<CommentType> rhsComment;
            rhsComment = (((that.comment!= null)&&(!that.comment.isEmpty()))?that.getComment():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "comment", lhsComment), LocatorUtils.property(thatLocator, "comment", rhsComment), lhsComment, rhsComment)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
