//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 01:58:58 PM MSK 
//


package eu.nimble.service.model.ubl.commonaggregatecomponents;

import eu.nimble.service.model.ubl.commonbasiccomponents.CodeType;
import eu.nimble.service.model.ubl.commonbasiccomponents.QuantityType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for EnvironmentalEmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvironmentalEmissionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}EnvironmentalEmissionTypeCode"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ValueMeasure"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvironmentalEmissionType", propOrder = {
    "environmentalEmissionTypeCode",
    "valueMeasure"
})
@Entity(name = "EnvironmentalEmissionType")
@Table(name = "ENVIRONMENTAL_EMISSION_TYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class EnvironmentalEmissionType
    implements Serializable, Equals
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EnvironmentalEmissionTypeCode", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected CodeType environmentalEmissionTypeCode;
    @XmlElement(name = "ValueMeasure", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected QuantityType valueMeasure;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the environmentalEmissionTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    @ManyToOne(targetEntity = CodeType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ENVIRONMENTAL_EMISSION_TYPE__1")
    public CodeType getEnvironmentalEmissionTypeCode() {
        return environmentalEmissionTypeCode;
    }

    /**
     * Sets the value of the environmentalEmissionTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setEnvironmentalEmissionTypeCode(CodeType value) {
        this.environmentalEmissionTypeCode = value;
    }

    /**
     * Gets the value of the valueMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    @ManyToOne(targetEntity = QuantityType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "VALUE_MEASURE_ENVIRONMENTAL__0")
    public QuantityType getValueMeasure() {
        return valueMeasure;
    }

    /**
     * Sets the value of the valueMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setValueMeasure(QuantityType value) {
        this.valueMeasure = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EnvironmentalEmissionType that = ((EnvironmentalEmissionType) object);
        {
            CodeType lhsEnvironmentalEmissionTypeCode;
            lhsEnvironmentalEmissionTypeCode = this.getEnvironmentalEmissionTypeCode();
            CodeType rhsEnvironmentalEmissionTypeCode;
            rhsEnvironmentalEmissionTypeCode = that.getEnvironmentalEmissionTypeCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "environmentalEmissionTypeCode", lhsEnvironmentalEmissionTypeCode), LocatorUtils.property(thatLocator, "environmentalEmissionTypeCode", rhsEnvironmentalEmissionTypeCode), lhsEnvironmentalEmissionTypeCode, rhsEnvironmentalEmissionTypeCode)) {
                return false;
            }
        }
        {
            QuantityType lhsValueMeasure;
            lhsValueMeasure = this.getValueMeasure();
            QuantityType rhsValueMeasure;
            rhsValueMeasure = that.getValueMeasure();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "valueMeasure", lhsValueMeasure), LocatorUtils.property(thatLocator, "valueMeasure", rhsValueMeasure), lhsValueMeasure, rhsValueMeasure)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
