//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.03 at 01:40:28 PM MSK 
//


package eu.nimble.service.model.ubl.commonaggregatecomponents;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.nimble.service.model.ubl.commonbasiccomponents.AmountType;
import eu.nimble.service.model.ubl.commonbasiccomponents.QuantityType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for LCPAOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LCPAOutputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}LifeCycleCost"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}OperationCostsPerYear"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CapexOpexRelation"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LCPAOutputType", propOrder = {
    "lifeCycleCost",
    "operationCostsPerYear",
    "capexOpexRelation"
})
@Entity(name = "LCPAOutputType")
@Table(name = "LCPAOUTPUT_TYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class LCPAOutputType
    implements Serializable, Equals
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LifeCycleCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected AmountType lifeCycleCost;
    @XmlElement(name = "OperationCostsPerYear", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected AmountType operationCostsPerYear;
    @XmlElement(name = "CapexOpexRelation", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected QuantityType capexOpexRelation;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the lifeCycleCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LIFE_CYCLE_COST_LCPAOUTPUT_T_0")
    public AmountType getLifeCycleCost() {
        return lifeCycleCost;
    }

    /**
     * Sets the value of the lifeCycleCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setLifeCycleCost(AmountType value) {
        this.lifeCycleCost = value;
    }

    /**
     * Gets the value of the operationCostsPerYear property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OPERATION_COSTS_PER_YEAR_LCP_0")
    public AmountType getOperationCostsPerYear() {
        return operationCostsPerYear;
    }

    /**
     * Sets the value of the operationCostsPerYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setOperationCostsPerYear(AmountType value) {
        this.operationCostsPerYear = value;
    }

    /**
     * Gets the value of the capexOpexRelation property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    @ManyToOne(targetEntity = QuantityType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CAPEX_OPEX_RELATION_LCPAOUTP_0")
    public QuantityType getCapexOpexRelation() {
        return capexOpexRelation;
    }

    /**
     * Sets the value of the capexOpexRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setCapexOpexRelation(QuantityType value) {
        this.capexOpexRelation = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final LCPAOutputType that = ((LCPAOutputType) object);
        {
            AmountType lhsLifeCycleCost;
            lhsLifeCycleCost = this.getLifeCycleCost();
            AmountType rhsLifeCycleCost;
            rhsLifeCycleCost = that.getLifeCycleCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lifeCycleCost", lhsLifeCycleCost), LocatorUtils.property(thatLocator, "lifeCycleCost", rhsLifeCycleCost), lhsLifeCycleCost, rhsLifeCycleCost)) {
                return false;
            }
        }
        {
            AmountType lhsOperationCostsPerYear;
            lhsOperationCostsPerYear = this.getOperationCostsPerYear();
            AmountType rhsOperationCostsPerYear;
            rhsOperationCostsPerYear = that.getOperationCostsPerYear();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operationCostsPerYear", lhsOperationCostsPerYear), LocatorUtils.property(thatLocator, "operationCostsPerYear", rhsOperationCostsPerYear), lhsOperationCostsPerYear, rhsOperationCostsPerYear)) {
                return false;
            }
        }
        {
            QuantityType lhsCapexOpexRelation;
            lhsCapexOpexRelation = this.getCapexOpexRelation();
            QuantityType rhsCapexOpexRelation;
            rhsCapexOpexRelation = that.getCapexOpexRelation();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "capexOpexRelation", lhsCapexOpexRelation), LocatorUtils.property(thatLocator, "capexOpexRelation", rhsCapexOpexRelation), lhsCapexOpexRelation, rhsCapexOpexRelation)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
