//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.26 at 02:34:59 PM MSK 
//


package eu.nimble.service.model.ubl.commonaggregatecomponents;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.nimble.service.model.ubl.commonbasiccomponents.AmountType;
import eu.nimble.service.model.ubl.commonbasiccomponents.QuantityType;
import org.hibernate.annotations.Cascade;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for LCPAInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LCPAInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}LifeCycleLength" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PurchasingPrice" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}AssemblyCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TransportCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ConsumableCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}EnergyConsumptionCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}MaintenanceCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}SparePartCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}EndOfLifeCost" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AdditionalLCPAInputDetail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LCPAInputType", propOrder = {
    "lifeCycleLength",
    "purchasingPrice",
    "assemblyCost",
    "transportCost",
    "consumableCost",
    "energyConsumptionCost",
    "maintenanceCost",
    "sparePartCost",
    "endOfLifeCost",
    "additionalLCPAInputDetail"
})
@Entity(name = "LCPAInputType")
@Table(name = "LCPAINPUT_TYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class LCPAInputType
    implements Serializable, Equals
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LifeCycleLength", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected QuantityType lifeCycleLength;
    @XmlElement(name = "PurchasingPrice", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType purchasingPrice;
    @XmlElement(name = "AssemblyCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType assemblyCost;
    @XmlElement(name = "TransportCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType transportCost;
    @XmlElement(name = "ConsumableCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType consumableCost;
    @XmlElement(name = "EnergyConsumptionCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType energyConsumptionCost;
    @XmlElement(name = "MaintenanceCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType maintenanceCost;
    @XmlElement(name = "SparePartCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType sparePartCost;
    @XmlElement(name = "EndOfLifeCost", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected AmountType endOfLifeCost;
    @XmlElement(name = "AdditionalLCPAInputDetail")
    protected List<MultiTypeValueType> additionalLCPAInputDetail;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the lifeCycleLength property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    @ManyToOne(targetEntity = QuantityType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "LIFE_CYCLE_LENGTH_LCPAINPUT__0")
    public QuantityType getLifeCycleLength() {
        return lifeCycleLength;
    }

    /**
     * Sets the value of the lifeCycleLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setLifeCycleLength(QuantityType value) {
        this.lifeCycleLength = value;
    }

    /**
     * Gets the value of the purchasingPrice property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "PURCHASING_PRICE_LCPAINPUT_T_0")
    public AmountType getPurchasingPrice() {
        return purchasingPrice;
    }

    /**
     * Sets the value of the purchasingPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPurchasingPrice(AmountType value) {
        this.purchasingPrice = value;
    }

    /**
     * Gets the value of the assemblyCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "ASSEMBLY_COST_LCPAINPUT_TYPE_0")
    public AmountType getAssemblyCost() {
        return assemblyCost;
    }

    /**
     * Sets the value of the assemblyCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAssemblyCost(AmountType value) {
        this.assemblyCost = value;
    }

    /**
     * Gets the value of the transportCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "TRANSPORT_COST_LCPAINPUT_TYP_0")
    public AmountType getTransportCost() {
        return transportCost;
    }

    /**
     * Sets the value of the transportCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTransportCost(AmountType value) {
        this.transportCost = value;
    }

    /**
     * Gets the value of the consumableCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "CONSUMABLE_COST_LCPAINPUT_TY_0")
    public AmountType getConsumableCost() {
        return consumableCost;
    }

    /**
     * Sets the value of the consumableCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setConsumableCost(AmountType value) {
        this.consumableCost = value;
    }

    /**
     * Gets the value of the energyConsumptionCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "ENERGY_CONSUMPTION_COST_LCPA_0")
    public AmountType getEnergyConsumptionCost() {
        return energyConsumptionCost;
    }

    /**
     * Sets the value of the energyConsumptionCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setEnergyConsumptionCost(AmountType value) {
        this.energyConsumptionCost = value;
    }

    /**
     * Gets the value of the maintenanceCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "MAINTENANCE_COST_LCPAINPUT_T_0")
    public AmountType getMaintenanceCost() {
        return maintenanceCost;
    }

    /**
     * Sets the value of the maintenanceCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setMaintenanceCost(AmountType value) {
        this.maintenanceCost = value;
    }

    /**
     * Gets the value of the sparePartCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "SPARE_PART_COST_LCPAINPUT_TY_0")
    public AmountType getSparePartCost() {
        return sparePartCost;
    }

    /**
     * Sets the value of the sparePartCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSparePartCost(AmountType value) {
        this.sparePartCost = value;
    }

    /**
     * Gets the value of the endOfLifeCost property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    @ManyToOne(targetEntity = AmountType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "END_OF_LIFE_COST_LCPAINPUT_T_0")
    public AmountType getEndOfLifeCost() {
        return endOfLifeCost;
    }

    /**
     * Sets the value of the endOfLifeCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setEndOfLifeCost(AmountType value) {
        this.endOfLifeCost = value;
    }

    /**
     * Gets the value of the additionalLCPAInputDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalLCPAInputDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalLCPAInputDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiTypeValueType }
     * 
     * 
     */
    @OneToMany(orphanRemoval = true,targetEntity = MultiTypeValueType.class, cascade = {
        javax.persistence.CascadeType.ALL
    })
    @JoinColumn(name = "ADDITIONAL_LCPAINPUT_DETAIL__0")
    public List<MultiTypeValueType> getAdditionalLCPAInputDetail() {
        if (additionalLCPAInputDetail == null) {
            additionalLCPAInputDetail = new ArrayList<MultiTypeValueType>();
        }
        return this.additionalLCPAInputDetail;
    }

    /**
     * 
     * 
     */
    public void setAdditionalLCPAInputDetail(List<MultiTypeValueType> additionalLCPAInputDetail) {
        this.additionalLCPAInputDetail = additionalLCPAInputDetail;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final LCPAInputType that = ((LCPAInputType) object);
        {
            QuantityType lhsLifeCycleLength;
            lhsLifeCycleLength = this.getLifeCycleLength();
            QuantityType rhsLifeCycleLength;
            rhsLifeCycleLength = that.getLifeCycleLength();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lifeCycleLength", lhsLifeCycleLength), LocatorUtils.property(thatLocator, "lifeCycleLength", rhsLifeCycleLength), lhsLifeCycleLength, rhsLifeCycleLength)) {
                return false;
            }
        }
        {
            AmountType lhsPurchasingPrice;
            lhsPurchasingPrice = this.getPurchasingPrice();
            AmountType rhsPurchasingPrice;
            rhsPurchasingPrice = that.getPurchasingPrice();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "purchasingPrice", lhsPurchasingPrice), LocatorUtils.property(thatLocator, "purchasingPrice", rhsPurchasingPrice), lhsPurchasingPrice, rhsPurchasingPrice)) {
                return false;
            }
        }
        {
            AmountType lhsAssemblyCost;
            lhsAssemblyCost = this.getAssemblyCost();
            AmountType rhsAssemblyCost;
            rhsAssemblyCost = that.getAssemblyCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "assemblyCost", lhsAssemblyCost), LocatorUtils.property(thatLocator, "assemblyCost", rhsAssemblyCost), lhsAssemblyCost, rhsAssemblyCost)) {
                return false;
            }
        }
        {
            AmountType lhsTransportCost;
            lhsTransportCost = this.getTransportCost();
            AmountType rhsTransportCost;
            rhsTransportCost = that.getTransportCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "transportCost", lhsTransportCost), LocatorUtils.property(thatLocator, "transportCost", rhsTransportCost), lhsTransportCost, rhsTransportCost)) {
                return false;
            }
        }
        {
            AmountType lhsConsumableCost;
            lhsConsumableCost = this.getConsumableCost();
            AmountType rhsConsumableCost;
            rhsConsumableCost = that.getConsumableCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "consumableCost", lhsConsumableCost), LocatorUtils.property(thatLocator, "consumableCost", rhsConsumableCost), lhsConsumableCost, rhsConsumableCost)) {
                return false;
            }
        }
        {
            AmountType lhsEnergyConsumptionCost;
            lhsEnergyConsumptionCost = this.getEnergyConsumptionCost();
            AmountType rhsEnergyConsumptionCost;
            rhsEnergyConsumptionCost = that.getEnergyConsumptionCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "energyConsumptionCost", lhsEnergyConsumptionCost), LocatorUtils.property(thatLocator, "energyConsumptionCost", rhsEnergyConsumptionCost), lhsEnergyConsumptionCost, rhsEnergyConsumptionCost)) {
                return false;
            }
        }
        {
            AmountType lhsMaintenanceCost;
            lhsMaintenanceCost = this.getMaintenanceCost();
            AmountType rhsMaintenanceCost;
            rhsMaintenanceCost = that.getMaintenanceCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maintenanceCost", lhsMaintenanceCost), LocatorUtils.property(thatLocator, "maintenanceCost", rhsMaintenanceCost), lhsMaintenanceCost, rhsMaintenanceCost)) {
                return false;
            }
        }
        {
            AmountType lhsSparePartCost;
            lhsSparePartCost = this.getSparePartCost();
            AmountType rhsSparePartCost;
            rhsSparePartCost = that.getSparePartCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sparePartCost", lhsSparePartCost), LocatorUtils.property(thatLocator, "sparePartCost", rhsSparePartCost), lhsSparePartCost, rhsSparePartCost)) {
                return false;
            }
        }
        {
            AmountType lhsEndOfLifeCost;
            lhsEndOfLifeCost = this.getEndOfLifeCost();
            AmountType rhsEndOfLifeCost;
            rhsEndOfLifeCost = that.getEndOfLifeCost();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "endOfLifeCost", lhsEndOfLifeCost), LocatorUtils.property(thatLocator, "endOfLifeCost", rhsEndOfLifeCost), lhsEndOfLifeCost, rhsEndOfLifeCost)) {
                return false;
            }
        }
        {
            List<MultiTypeValueType> lhsAdditionalLCPAInputDetail;
            lhsAdditionalLCPAInputDetail = (((this.additionalLCPAInputDetail!= null)&&(!this.additionalLCPAInputDetail.isEmpty()))?this.getAdditionalLCPAInputDetail():null);
            List<MultiTypeValueType> rhsAdditionalLCPAInputDetail;
            rhsAdditionalLCPAInputDetail = (((that.additionalLCPAInputDetail!= null)&&(!that.additionalLCPAInputDetail.isEmpty()))?that.getAdditionalLCPAInputDetail():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "additionalLCPAInputDetail", lhsAdditionalLCPAInputDetail), LocatorUtils.property(thatLocator, "additionalLCPAInputDetail", rhsAdditionalLCPAInputDetail), lhsAdditionalLCPAInputDetail, rhsAdditionalLCPAInputDetail)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

}
