//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.10 at 10:02:02 AM EET 
//


package eu.nimble.service.model.ubl.commonaggregatecomponents;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.nimble.service.model.ubl.commonbasiccomponents.TextType;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for PriceOptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceOptionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Incoterms" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}SpecialTerms"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}EstimatedDeliveryPeriod"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AdditionalItemProperty" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}PaymentMeans" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}PaymentTerms"/&gt;
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}ItemLocationQuantity"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceOptionType", propOrder = {
    "name",
    "incoterms",
    "specialTerms",
    "estimatedDeliveryPeriod",
    "additionalItemProperty",
    "paymentMeans",
    "paymentTerms",
    "itemLocationQuantity"
})
@Entity(name = "PriceOptionType")
@Table(name = "PRICE_OPTION_TYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class PriceOptionType
    implements Serializable, Equals
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Name", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")
    protected TextType name;
    @XmlElement(name = "Incoterms", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected List<String> incoterms;
    @XmlElement(name = "SpecialTerms", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", required = true)
    protected TextType specialTerms;
    @XmlElement(name = "EstimatedDeliveryPeriod", required = true)
    protected PeriodType estimatedDeliveryPeriod;
    @XmlElement(name = "AdditionalItemProperty", required = true)
    protected List<ItemPropertyType> additionalItemProperty;
    @XmlElement(name = "PaymentMeans", required = true)
    protected List<PaymentMeansType> paymentMeans;
    @XmlElement(name = "PaymentTerms", required = true)
    protected PaymentTermsType paymentTerms;
    @XmlElement(name = "ItemLocationQuantity", required = true)
    protected ItemLocationQuantityType itemLocationQuantity;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<PriceOptionTypeIncotermsItem> incotermsItems;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    @ManyToOne(targetEntity = TextType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "NAME__PRICE_OPTION_TYPE_HJID")
    public TextType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setName(TextType value) {
        this.name = value;
    }

    /**
     * Gets the value of the incoterms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incoterms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncoterms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getIncoterms() {
        if (incoterms == null) {
            incoterms = new ArrayList<String>();
        }
        return this.incoterms;
    }

    /**
     * 
     * 
     */
    public void setIncoterms(List<String> incoterms) {
        this.incoterms = incoterms;
    }

    /**
     * Gets the value of the specialTerms property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    @ManyToOne(targetEntity = TextType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SPECIAL_TERMS_PRICE_OPTION_T_0")
    public TextType getSpecialTerms() {
        return specialTerms;
    }

    /**
     * Sets the value of the specialTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setSpecialTerms(TextType value) {
        this.specialTerms = value;
    }

    /**
     * Gets the value of the estimatedDeliveryPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    @ManyToOne(targetEntity = PeriodType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ESTIMATED_DELIVERY_PERIOD_PR_0")
    public PeriodType getEstimatedDeliveryPeriod() {
        return estimatedDeliveryPeriod;
    }

    /**
     * Sets the value of the estimatedDeliveryPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setEstimatedDeliveryPeriod(PeriodType value) {
        this.estimatedDeliveryPeriod = value;
    }

    /**
     * Gets the value of the additionalItemProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalItemProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalItemProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemPropertyType }
     * 
     * 
     */
    @OneToMany(targetEntity = ItemPropertyType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ADDITIONAL_ITEM_PROPERTY_PRI_0")
    public List<ItemPropertyType> getAdditionalItemProperty() {
        if (additionalItemProperty == null) {
            additionalItemProperty = new ArrayList<ItemPropertyType>();
        }
        return this.additionalItemProperty;
    }

    /**
     * 
     * 
     */
    public void setAdditionalItemProperty(List<ItemPropertyType> additionalItemProperty) {
        this.additionalItemProperty = additionalItemProperty;
    }

    /**
     * Gets the value of the paymentMeans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentMeans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentMeans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentMeansType }
     * 
     * 
     */
    @OneToMany(targetEntity = PaymentMeansType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PAYMENT_MEANS_PRICE_OPTION_T_0")
    public List<PaymentMeansType> getPaymentMeans() {
        if (paymentMeans == null) {
            paymentMeans = new ArrayList<PaymentMeansType>();
        }
        return this.paymentMeans;
    }

    /**
     * 
     * 
     */
    public void setPaymentMeans(List<PaymentMeansType> paymentMeans) {
        this.paymentMeans = paymentMeans;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTermsType }
     *     
     */
    @ManyToOne(targetEntity = PaymentTermsType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PAYMENT_TERMS_PRICE_OPTION_T_0")
    public PaymentTermsType getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTermsType }
     *     
     */
    public void setPaymentTerms(PaymentTermsType value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the itemLocationQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ItemLocationQuantityType }
     *     
     */
    @ManyToOne(targetEntity = ItemLocationQuantityType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEM_LOCATION_QUANTITY_PRICE_0")
    public ItemLocationQuantityType getItemLocationQuantity() {
        return itemLocationQuantity;
    }

    /**
     * Sets the value of the itemLocationQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemLocationQuantityType }
     *     
     */
    public void setItemLocationQuantity(ItemLocationQuantityType value) {
        this.itemLocationQuantity = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PriceOptionType that = ((PriceOptionType) object);
        {
            TextType lhsName;
            lhsName = this.getName();
            TextType rhsName;
            rhsName = that.getName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "name", lhsName), LocatorUtils.property(thatLocator, "name", rhsName), lhsName, rhsName)) {
                return false;
            }
        }
        {
            List<String> lhsIncoterms;
            lhsIncoterms = (((this.incoterms!= null)&&(!this.incoterms.isEmpty()))?this.getIncoterms():null);
            List<String> rhsIncoterms;
            rhsIncoterms = (((that.incoterms!= null)&&(!that.incoterms.isEmpty()))?that.getIncoterms():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "incoterms", lhsIncoterms), LocatorUtils.property(thatLocator, "incoterms", rhsIncoterms), lhsIncoterms, rhsIncoterms)) {
                return false;
            }
        }
        {
            TextType lhsSpecialTerms;
            lhsSpecialTerms = this.getSpecialTerms();
            TextType rhsSpecialTerms;
            rhsSpecialTerms = that.getSpecialTerms();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "specialTerms", lhsSpecialTerms), LocatorUtils.property(thatLocator, "specialTerms", rhsSpecialTerms), lhsSpecialTerms, rhsSpecialTerms)) {
                return false;
            }
        }
        {
            PeriodType lhsEstimatedDeliveryPeriod;
            lhsEstimatedDeliveryPeriod = this.getEstimatedDeliveryPeriod();
            PeriodType rhsEstimatedDeliveryPeriod;
            rhsEstimatedDeliveryPeriod = that.getEstimatedDeliveryPeriod();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "estimatedDeliveryPeriod", lhsEstimatedDeliveryPeriod), LocatorUtils.property(thatLocator, "estimatedDeliveryPeriod", rhsEstimatedDeliveryPeriod), lhsEstimatedDeliveryPeriod, rhsEstimatedDeliveryPeriod)) {
                return false;
            }
        }
        {
            List<ItemPropertyType> lhsAdditionalItemProperty;
            lhsAdditionalItemProperty = (((this.additionalItemProperty!= null)&&(!this.additionalItemProperty.isEmpty()))?this.getAdditionalItemProperty():null);
            List<ItemPropertyType> rhsAdditionalItemProperty;
            rhsAdditionalItemProperty = (((that.additionalItemProperty!= null)&&(!that.additionalItemProperty.isEmpty()))?that.getAdditionalItemProperty():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "additionalItemProperty", lhsAdditionalItemProperty), LocatorUtils.property(thatLocator, "additionalItemProperty", rhsAdditionalItemProperty), lhsAdditionalItemProperty, rhsAdditionalItemProperty)) {
                return false;
            }
        }
        {
            List<PaymentMeansType> lhsPaymentMeans;
            lhsPaymentMeans = (((this.paymentMeans!= null)&&(!this.paymentMeans.isEmpty()))?this.getPaymentMeans():null);
            List<PaymentMeansType> rhsPaymentMeans;
            rhsPaymentMeans = (((that.paymentMeans!= null)&&(!that.paymentMeans.isEmpty()))?that.getPaymentMeans():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "paymentMeans", lhsPaymentMeans), LocatorUtils.property(thatLocator, "paymentMeans", rhsPaymentMeans), lhsPaymentMeans, rhsPaymentMeans)) {
                return false;
            }
        }
        {
            PaymentTermsType lhsPaymentTerms;
            lhsPaymentTerms = this.getPaymentTerms();
            PaymentTermsType rhsPaymentTerms;
            rhsPaymentTerms = that.getPaymentTerms();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "paymentTerms", lhsPaymentTerms), LocatorUtils.property(thatLocator, "paymentTerms", rhsPaymentTerms), lhsPaymentTerms, rhsPaymentTerms)) {
                return false;
            }
        }
        {
            ItemLocationQuantityType lhsItemLocationQuantity;
            lhsItemLocationQuantity = this.getItemLocationQuantity();
            ItemLocationQuantityType rhsItemLocationQuantity;
            rhsItemLocationQuantity = that.getItemLocationQuantity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itemLocationQuantity", lhsItemLocationQuantity), LocatorUtils.property(thatLocator, "itemLocationQuantity", rhsItemLocationQuantity), lhsItemLocationQuantity, rhsItemLocationQuantity)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = PriceOptionTypeIncotermsItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INCOTERMS_ITEMS_PRICE_OPTION_0")
    public List<PriceOptionTypeIncotermsItem> getIncotermsItems() {
        if (this.incotermsItems == null) {
            this.incotermsItems = new ArrayList<PriceOptionTypeIncotermsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.incoterms)) {
            this.incoterms = ItemUtils.wrap(this.incoterms, this.incotermsItems, PriceOptionTypeIncotermsItem.class);
        }
        return this.incotermsItems;
    }

    public void setIncotermsItems(List<PriceOptionTypeIncotermsItem> value) {
        this.incoterms = null;
        this.incotermsItems = null;
        this.incotermsItems = value;
        if (this.incotermsItems == null) {
            this.incotermsItems = new ArrayList<PriceOptionTypeIncotermsItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.incoterms)) {
            this.incoterms = ItemUtils.wrap(this.incoterms, this.incotermsItems, PriceOptionTypeIncotermsItem.class);
        }
    }

}
